export const holes = {
  death: [
    "Accident",
    "Animal",
    "Beating",
    "Beheading",
    "Bladed",
    "Burning",
    "Cartel",
    "Combat",
    "Compilation",
    "Disaster",
    "Drowning",
    "Electricity",
    "Execution",
    "Explosions",
    "Falling",
    "Industrial",
    "ISIS",
    "Maiming",
    "Police",
    "Shooting",
    "Suicide",
    "Vehicle",
    "Other",
  ],
  gore: ["Aftermath", "Fights", "Gore", "Medical", "Request", "Self-Harm"],
  social: ["Discussion", "Meta", "Music", "Pets", "Social"],
  activeConflicts: ["Slavshit", "Sandshit"],
};

export const localVideoFileNames = [
  "Evil Teen SHOCKED By Horrible Detectives - YouTube - Google Chrome 2023-12-19 14-59-50.mp4",
  "Melancholia.2011.1080i.BluRay.REMUX.AVC.DTS-HD.MA.5.1-CiNEPLEX.mkv 2023-12-30 20-31-02.mp4",
  "Nick@Nite The Oddities 90's Broadcast Reimagined - YouTube - Google Chrome 2023-12-20 14-24-43.mp4",
  "Testees - S1 · E1 - Google Chrome 2024-01-02 03-17-18.mp4",
  "When a Mom Discovers Every Parent's Worst Nightmare - YouTube - Google Chrome 2023-12-30 15-19-53.mp4",
  "Who's on the FBI's Most Wanted List and Why - YouTube - Google Chrome 2023-12-23 01-11-18.mp4",
  "Who's on the FBI's Most Wanted List and Why - YouTube - Google Chrome 2023-12-23 01-11-27.mp4",
];

export const randomlyGeneratedUsernames = [
  "MysticJaguar87",
  "QuantumPenguin",
  "NebulaNinja",
  "SapphireDragon23",
  "GalacticGiraffe",
  "CyberPhoenixX",
  "CelestialFox42",
  "ShadowSpectre",
  "LunaLynx19",
  "ThunderTiger99",
  "SolarSphinx",
  "VelvetVortex",
  "StarryWhisper",
  "BlazeBison",
  "AuroraArrow",
  "CrimsonComet",
  "NovaNoodle",
  "EmberEagle",
  "FrostyFalcon",
  "PixelP",
];